sudo: false
language: node_js
node_js:
  - "stable"
  - 14
  - 12
  - 10
  - 4.2
  - 0.12
  - 0.10
  - 0.8

arch:
  - amd64
  - ppc64le

before_install:
  - travis_retry npm install -g npm@2.14.5
  - travis_retry npm install

script:
  - npm test

matrix:
  exclude:
    - arch: ppc64le
      node_js: "0.8"
    - arch: ppc64le
      node_js: "0.10"
    - arch: ppc64le
      node_js: "0.12"
    - arch: ppc64le
      node_js: "stable"
  allow_failures:
    - node_js: "0.8"

#notifications:
#  email:
#    - charlie.robbins@gmail.com

